// Release notes (patch notes) of the Desktop distribution.
//
//   node scripts/release-notes.mjs --write           # regenerate the embedded module
//   node scripts/release-notes.mjs --check           # note for the canonical version exists AND the embedded module is fresh
//   node scripts/release-notes.mjs [--version=<v>]   # print the note of a version (default: the canonical one)
//
// Source of truth: one Markdown file per release in `desktop/release-notes/`,
// named after the base version (`0.1.0.md`), written for humans in plain French.
// The embedded module (`dashboard/src/releaseNotes.generated.ts`) is generated
// from them and committed, so the Dashboard bundle carries the notes without any
// network call. A pre-release channel build (`0.1.0-dev.42`) resolves to its base
// version (`0.1.0`), so one file covers a whole release line. A release without
// its note is refused by `--check` (the release gate).
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { pathToFileURL } from "node:url";
import { arg, dashboardDir, desktopDir, flag } from "./lib.mjs";
import { canonicalVersion } from "./version.mjs";

export const releaseNotesDir = join(desktopDir, "release-notes");
export const generatedModulePath = join(dashboardDir, "src", "releaseNotes.generated.ts");
export const RELEASE_NOTES_SCHEMA = 1;

const BASE_VERSION = /^(\d+\.\d+\.\d+)(?:-[0-9A-Za-z.-]+)?$/;

/** The base `major.minor.patch` of a version: `0.1.0-dev.42` -> `0.1.0`. */
export function baseVersion(version) {
  const match = BASE_VERSION.exec(String(version).trim());
  if (!match) throw new Error(`not a semver version: ${version}`);
  return match[1];
}

function compareBaseVersions(a, b) {
  const left = a.split(".").map(Number);
  const right = b.split(".").map(Number);
  for (let index = 0; index < 3; index += 1) {
    const delta = (left[index] ?? 0) - (right[index] ?? 0);
    if (delta !== 0) return delta;
  }
  return 0;
}

/** Base versions that have a note file, ascending. */
export function noteVersions(dir = releaseNotesDir) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((name) => name.endsWith(".md"))
    .map((name) => name.slice(0, -3))
    .filter((version) => BASE_VERSION.test(version))
    .sort(compareBaseVersions);
}

/** The note of a version (its base), LF-normalized and trimmed, or `null`. */
export function readReleaseNote(version, dir = releaseNotesDir) {
  const file = join(dir, `${baseVersion(version)}.md`);
  if (!existsSync(file)) return null;
  const text = readFileSync(file, "utf8").replace(/\r\n/g, "\n").trim();
  return text === "" ? null : text;
}

/** The note of a version, or a hard error naming the missing file. */
export function requireReleaseNote(version, dir = releaseNotesDir) {
  const note = readReleaseNote(version, dir);
  if (note === null) {
    throw new Error(`missing release note for ${baseVersion(version)}: add ${join(dir, `${baseVersion(version)}.md`)}`);
  }
  return note;
}

/** The committed Dashboard module built from every note, LF-normalized. */
export function buildNotesModule(dir = releaseNotesDir) {
  const versions = noteVersions(dir);
  const entries = versions
    .map((version) => `  ${JSON.stringify(version)}: ${JSON.stringify(requireReleaseNote(version, dir))},`)
    .join("\n");
  return [
    "// Generated by desktop/scripts/release-notes.mjs --write — do not edit by hand.",
    "// Source of truth: desktop/release-notes/<version>.md.",
    `export const RELEASE_NOTES_SCHEMA = ${RELEASE_NOTES_SCHEMA};`,
    "",
    "export const RELEASE_NOTES: Record<string, string> = {",
    entries,
    "};",
    "",
    `export const RELEASE_NOTES_VERSIONS: readonly string[] = [${versions.map((version) => JSON.stringify(version)).join(", ")}];`,
    "",
  ].join("\n");
}

/** Fail when the committed module drifted from the note files. */
export function checkNotesModule(dir = releaseNotesDir, out = generatedModulePath) {
  const expected = buildNotesModule(dir);
  const current = existsSync(out) ? readFileSync(out, "utf8").replace(/\r\n/g, "\n") : "";
  if (current !== expected) {
    throw new Error(`${out} is out of date; run: node scripts/release-notes.mjs --write`);
  }
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    const version = arg("--version") ?? canonicalVersion();
    if (flag("--write")) {
      mkdirSync(dirname(generatedModulePath), { recursive: true });
      writeFileSync(generatedModulePath, buildNotesModule());
      console.log(`wrote ${generatedModulePath} (${noteVersions().length} version(s))`);
    } else if (flag("--check")) {
      requireReleaseNote(version);
      checkNotesModule();
      console.log(`release notes OK for ${baseVersion(version)}`);
    } else {
      console.log(readReleaseNote(version) ?? "");
    }
  } catch (error) {
    console.error(`✖ ${error.message}`);
    process.exitCode = 1;
  }
}
