// Generated by desktop/scripts/release-notes.mjs --write — do not edit by hand.
// Source of truth: desktop/release-notes/<version>.md.
export const RELEASE_NOTES_SCHEMA = 1;

export const RELEASE_NOTES: Record<string, string> = {
  "0.1.0": "# Version 0.1.0\n\nPremière version publique de Studi'OS Desktop.\n\n## Nouveautés\n\n- Un assistant vous guide au premier lancement : connexion à votre serveur, choix du projet et du dossier de travail.\n- L'assistant local est fourni avec l'application, rien à installer à la main.\n- Le tableau de bord réunit vos tâches, vos transferts de fichiers et la coordination avec l'autre poste.\n- Les mises à jour de l'application sont vérifiées avant d'être installées.\n\n## Bon à savoir\n\n- Pour retrouver la version, l'état de la connexion et un diagnostic exportable : « Réglages › Application ».\n- Cette fenêtre « Quoi de neuf » revient automatiquement après chaque mise à jour, et reste accessible depuis « Réglages › Application ».",
};

export const RELEASE_NOTES_VERSIONS: readonly string[] = ["0.1.0"];
