"""P7 onboarding E2E — scripted scenario and reproducible bootstrap metrics.

Automates the reference scenario (AI Bootstrap audit §7, roadmap §9): a blank
Godot repository is seeded with a minimal `.agents/` project source, the local
`bootstrap` generator produces the Claude Code / OpenCode / Codex projections,
and the run is measured. Deterministic: same inputs, same bytes, same numbers —
running twice with no source change is byte-identical.

Measured (roadmap §9 / gate P7):
- files and bytes produced by `sync` (by kind, by harness);
- the permanent bootstrap kept in the repository (`permanent_bootstrap`);
- the manual actions a human performs to onboard, then to add a harness;
- harness parity: OpenCode and Codex are added without recreating any `.agents/`
  source (the canonical files stay byte-identical).

The metrics are published in `docs/AI_BOOTSTRAP_P7_METRICS.json` (machine) and
`docs/AI_BOOTSTRAP_P7_METRICS.md` (human).

Usage:
    uv run python -m scripts.p7_onboarding_metrics --root . --check   # exit 1 if stale
    uv run python -m scripts.p7_onboarding_metrics --root . --apply   # (re)write it
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import sys
import tempfile
from pathlib import Path
from typing import Any

from studio_client.bootstrap import (
    MANIFEST_RELATIVE_PATH,
    PlannedFile,
    apply_files,
    make_manifest,
    manifest_path,
    observe,
    plan_files,
    write_manifest,
)
from studio_contracts.bootstrap import OnModified

METRICS_FORMAT = "studio.p7.onboarding-metrics/v1"
METRICS_RELATIVE_PATH = "docs/AI_BOOTSTRAP_P7_METRICS.json"

PROJECT_SLUG = "blank-godot"
PROJECT_NAME = "Blank Godot"
BASE_HARNESSES = ["claude-code"]
ADDED_HARNESSES = ["claude-code", "opencode", "codex"]

GODOT_PROJECT = (
    "; Engine configuration file.\n"
    "; Generated by Studio OS onboarding metrics.\n"
    "config_version=5\n\n"
    "[application]\n"
    'config/name="Blank Godot"\n'
)

GODOT_SCENE = '[gd_scene format=3]\n\n[node name="Main" type="Node2D"]\n'

GODOT_SCRIPT = "extends Node2D\n\nfunc _ready() -> void:\n\tpass\n"

PROJECT_RULE = (
    "---\n"
    "applies_to:\n"
    '  - "scripts/**/*.gd"\n'
    "---\n"
    "\n"
    "# Project conventions\n"
    "\n"
    "Keep the project-specific surface small; shared rules live in the Library.\n"
)

PROJECT_SKILL = (
    "---\n"
    "name: project-workflow\n"
    "description: Project-specific workflow for the blank Godot repository.\n"
    "---\n"
    "\n"
    "# Project workflow\n"
    "\n"
    "Read the managed block, resolve the project, then load Studio OS context on\n"
    "demand. Pure project-local skill; no harness or model reference.\n"
)

PROJECT_AGENT = (
    "---\n"
    "stable_key: project-agent\n"
    "title: Project Agent\n"
    "summary: Blank Godot project agent used to validate onboarding.\n"
    "intended_use: Use for any task in the blank Godot repository.\n"
    "edit_policy: deny\n"
    "tools: [read, grep, glob]\n"
    "rules: [project-conventions]\n"
    "skills: [project-workflow]\n"
    "---\n"
    "\n"
    "You work inside the blank Godot repository.\n"
    "\n"
    "Start from the managed block, then ask Studio OS for the context you need.\n"
)

MANUAL_ONBOARDING = [
    {
        "id": "init",
        "description": "Declare the target harnesses and project identity.",
        "command": (
            "studio-client bootstrap init --project-slug blank-godot "
            '--project-name "Blank Godot" --harness claude-code'
        ),
    },
    {
        "id": "sync",
        "description": "Generate the managed block and the projections.",
        "command": "studio-client bootstrap sync",
    },
    {
        "id": "open-harness",
        "description": "Open the harness at the repository root.",
        "command": "cd <repo> && claude",
    },
]

MANUAL_ADD_HARNESS = [
    {
        "id": "init-overwrite",
        "description": "Re-declare the harness set (adds OpenCode and Codex).",
        "command": (
            "studio-client bootstrap init --overwrite --harness claude-code "
            "--harness opencode --harness codex"
        ),
    },
    {
        "id": "sync",
        "description": "Regenerate the projections from the same sources.",
        "command": "studio-client bootstrap sync",
    },
]


def _norm(text: str) -> str:
    return text.replace("\r\n", "\n")


def _size(text: str) -> int:
    return len(_norm(text).encode("utf-8"))


def _files_size(root: Path, *, skip: set[str] | None = None) -> tuple[int, int]:
    skip = skip or set()
    count = 0
    total = 0
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        relative = path.relative_to(root).as_posix()
        if relative in skip:
            continue
        count += 1
        total += _size(path.read_text(encoding="utf-8", errors="surrogateescape"))
    return count, total


def _tree_digest(root: Path, *, skip: set[str] | None = None) -> str:
    skip = skip or set()
    digest = hashlib.sha256()
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        relative = path.relative_to(root).as_posix()
        if relative in skip:
            continue
        digest.update(relative.encode("utf-8"))
        digest.update(b"\0")
        digest.update(
            _norm(path.read_text(encoding="utf-8", errors="surrogateescape")).encode("utf-8")
        )
        digest.update(b"\0")
    return digest.hexdigest()


def _harness_of(path: str) -> str:
    if path.startswith(".claude/"):
        return "claude-code"
    if path.startswith(".opencode/"):
        return "opencode"
    if path.startswith(".codex/"):
        return "codex"
    return "shared"


def seed_blank_godot(root: Path) -> None:
    (root / "scenes").mkdir(parents=True, exist_ok=True)
    (root / "scripts").mkdir(parents=True, exist_ok=True)
    (root / "project.godot").write_text(GODOT_PROJECT, encoding="utf-8", newline="\n")
    (root / "scenes" / "main.tscn").write_text(GODOT_SCENE, encoding="utf-8", newline="\n")
    (root / "scripts" / "player.gd").write_text(GODOT_SCRIPT, encoding="utf-8", newline="\n")


def seed_minimal_agents(root: Path) -> None:
    rules = root / ".agents" / "rules"
    skill = root / ".agents" / "skills" / "project-workflow"
    definitions = root / ".agents" / "definitions"
    for directory in (rules, skill, definitions):
        directory.mkdir(parents=True, exist_ok=True)
    (rules / "project-conventions.md").write_text(PROJECT_RULE, encoding="utf-8", newline="\n")
    (skill / "SKILL.md").write_text(PROJECT_SKILL, encoding="utf-8", newline="\n")
    (definitions / "project-agent.md").write_text(PROJECT_AGENT, encoding="utf-8", newline="\n")


def _count_by(items: list[PlannedFile], key: Any) -> dict[str, dict[str, int]]:
    buckets: dict[str, dict[str, int]] = {}
    for item in items:
        name = key(item)
        bucket = buckets.setdefault(name, {"files": 0, "bytes": 0})
        bucket["files"] += 1
        bucket["bytes"] += _size(item.content)
    return buckets


def run_scenario() -> dict[str, Any]:
    """Execute the reference scenario on a throwaway blank repository."""
    workdir = Path(tempfile.mkdtemp(prefix="studio-p7-onboarding-"))
    try:
        seed_blank_godot(workdir)
        seed_minimal_agents(workdir)
        manifest_name = MANIFEST_RELATIVE_PATH.split("/", 1)[1]
        sources_before = _tree_digest(workdir / ".agents", skip={manifest_name})

        manifest = make_manifest(
            PROJECT_SLUG,
            PROJECT_NAME,
            BASE_HARNESSES,
            on_modified=OnModified.REFUSE,
        )
        write_manifest(workdir, manifest)
        base_planned = plan_files(workdir, manifest)
        base_report = observe(workdir, manifest, planned=base_planned)
        base_written = apply_files(
            workdir, manifest, base_report, planned=base_planned, confirm=True
        )

        manifest = make_manifest(
            PROJECT_SLUG,
            PROJECT_NAME,
            ADDED_HARNESSES,
            on_modified=OnModified.REFUSE,
        )
        write_manifest(workdir, manifest, overwrite=True)
        added_planned = plan_files(workdir, manifest)
        added_report = observe(workdir, manifest, planned=added_planned)
        added_written = apply_files(
            workdir, manifest, added_report, planned=added_planned, confirm=True
        )

        sources_after = _tree_digest(workdir / ".agents", skip={manifest_name})
        second_report = observe(workdir, manifest, planned=plan_files(workdir, manifest))
        second_written = apply_files(
            workdir,
            manifest,
            second_report,
            planned=plan_files(workdir, manifest),
            confirm=True,
        )

        projections = [item for item in added_planned if not item.block]
        blocks = [item for item in added_planned if item.block]
        agent_sources_files, agent_sources_bytes = _files_size(
            workdir / ".agents", skip={manifest_name}
        )
        manifest_bytes = _size(manifest_path(workdir).read_text(encoding="utf-8"))
        block_bytes = sum(_size(item.content) for item in blocks)

        codex_parity, opencode_parity = harness_parity(workdir)

        metrics: dict[str, Any] = {
            "format": METRICS_FORMAT,
            "scenario": {
                "project": PROJECT_SLUG,
                "phases": [
                    "blank-godot",
                    "init-claude-code",
                    "sync",
                    "add-opencode-codex",
                    "sync-idempotent",
                ],
                "harnesses": ADDED_HARNESSES,
            },
            "sync_output": {
                "files": len(added_planned),
                "bytes": sum(_size(item.content) for item in added_planned),
                "by_kind": _count_by(added_planned, lambda item: item.kind),
                "by_harness": _count_by(added_planned, lambda item: _harness_of(item.path)),
                "first_harness_files": len(base_written),
                "added_harness_files": len(added_written),
                "idempotent_second_sync_writes": len(second_written),
            },
            "permanent_bootstrap": {
                "files": agent_sources_files + 1 + len(blocks),
                "bytes": agent_sources_bytes + manifest_bytes + block_bytes,
                "breakdown": {
                    "agents_sources": {"files": agent_sources_files, "bytes": agent_sources_bytes},
                    "manifest": {"files": 1, "bytes": manifest_bytes},
                    "managed_blocks": {"files": len(blocks), "bytes": block_bytes},
                },
            },
            "generated_projections": {
                "files": len(projections),
                "bytes": sum(_size(item.content) for item in projections),
            },
            "harness_parity": {
                "sources_unchanged": sources_before == sources_after,
                "opencode_added_without_source_change": opencode_parity,
                "codex_added_without_source_change": codex_parity,
            },
            "manual_actions": {
                "onboarding": {"count": len(MANUAL_ONBOARDING), "items": MANUAL_ONBOARDING},
                "add_harness": {"count": len(MANUAL_ADD_HARNESS), "items": MANUAL_ADD_HARNESS},
            },
            "second_agent_resume": {
                "covered_by": "tests/mcp/test_agent_loop_sync_e2e.py",
                "bootstrap_is_harness_neutral": opencode_parity and codex_parity,
            },
            "on_demand_context": {
                "counted_here": False,
                "note": (
                    "Library/Resolution context is fetched live by "
                    "studio_prepare_context; it is not parked in the repository."
                ),
            },
        }
        return metrics
    finally:
        shutil.rmtree(workdir, ignore_errors=True)


def harness_parity(root: Path) -> tuple[bool, bool]:
    """True when a harness projection equals the canonical `.agents/` source,
    proving it was generated (not authored as an independent source)."""
    skill_source = _norm(
        (root / ".agents" / "skills" / "project-workflow" / "SKILL.md").read_text(encoding="utf-8")
    )
    result: dict[str, bool] = {}
    for harness, skills_dir in (
        ("opencode", ".opencode/skills"),
        ("codex", ".codex/skills"),
    ):
        projected = root / skills_dir / "project-workflow" / "SKILL.md"
        result[harness] = (
            projected.is_file() and _norm(projected.read_text(encoding="utf-8")) == skill_source
        )
    return result["codex"], result["opencode"]


def render_json(metrics: dict[str, Any]) -> str:
    return json.dumps(metrics, indent=2, ensure_ascii=False, sort_keys=False) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", required=True, type=Path)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument(
        "--check", action="store_true", help="exit 1 if the published metrics are stale"
    )
    mode.add_argument("--apply", action="store_true", help="(re)write the published metrics")
    parser.add_argument("--stdout", action="store_true", help="also print the JSON to stdout")
    args = parser.parse_args()

    rendered = render_json(run_scenario())
    target = args.root / METRICS_RELATIVE_PATH
    if args.stdout:
        sys.stdout.write(rendered)
    if args.apply:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(rendered, encoding="utf-8", newline="\n")
        print(f"Wrote {METRICS_RELATIVE_PATH}.")
        return 0
    current = target.read_text(encoding="utf-8") if target.is_file() else ""
    if _norm(current) != rendered:
        print(f"{METRICS_RELATIVE_PATH} is stale -- rerun with --apply.")
        return 1
    print(f"{METRICS_RELATIVE_PATH} is up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
